#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr  1 18:22:57 2023

@author: tyler
"""

from twilio.rest import Client

account_sid = 'ACda783f7ce79c6f70304660fd0be80e9f'
auth_token = 'f10030f18551aacee9dd17d0e90c4072'
client = Client(account_sid, auth_token)

def pHmessage(pH, sender, recipient):
    if pH < 6.0:
        messageLow = client.messages.create(body='The ph in your area was measured at ' + str(pH) + '. This is unusually low',
            from_= sender,
            to = recipient)
        print(messageLow.sid)
    elif pH > 9.0:
        messageHigh = client.messages.create(body='The ph in your area was measured at ' + str(pH) + '. This is unusually high',
            from_= sender,
            to = recipient)
        print(messageHigh.sid)
    else:
        exit()
        
pHmessage(10.0,'18333031367','19738421069' )